In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

In [3]:
dataset = pd.read_csv("./data/neural_network/Churn_Modelling.csv")

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [8]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# initialize the ann
ann = tf.keras.models.Sequential()

In [12]:
# add an input layer and 1st hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [13]:
# add a 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [14]:
# add an output layer
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [15]:
# compile the ann
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [16]:
# train the ann on the training dataset
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 594us/step - loss: 0.5773 - accuracy: 0.7371
Epoch 2/100
250/250 [==============================] - 0s 588us/step - loss: 0.4831 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 564us/step - loss: 0.4563 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 0s 553us/step - loss: 0.4405 - accuracy: 0.7974
Epoch 5/100
250/250 [==============================] - 0s 615us/step - loss: 0.4312 - accuracy: 0.7990
Epoch 6/100
250/250 [==============================] - 0s 583us/step - loss: 0.4249 - accuracy: 0.7995
Epoch 7/100
250/250 [==============================] - 0s 584us/step - loss: 0.4206 - accuracy: 0.8015
Epoch 8/100
250/250 [==============================] - 0s 577us/step - loss: 0.4169 - accuracy: 0.8052
Epoch 9/100
250/250 [==============================] - 0s 601us/step - loss: 0.4127 - accuracy: 0.8071
Epoch 10/100
250/250 [==============================] - 0s 539us/step - l

250/250 [==============================] - 0s 559us/step - loss: 0.3374 - accuracy: 0.8622
Epoch 80/100
250/250 [==============================] - 0s 631us/step - loss: 0.3374 - accuracy: 0.86240s - loss: 0.3329 - accuracy: 0.
Epoch 81/100
250/250 [==============================] - 0s 666us/step - loss: 0.3369 - accuracy: 0.8645
Epoch 82/100
250/250 [==============================] - 0s 624us/step - loss: 0.3369 - accuracy: 0.8624
Epoch 83/100
250/250 [==============================] - 0s 519us/step - loss: 0.3369 - accuracy: 0.8621
Epoch 84/100
250/250 [==============================] - 0s 551us/step - loss: 0.3369 - accuracy: 0.8629
Epoch 85/100
250/250 [==============================] - 0s 563us/step - loss: 0.3368 - accuracy: 0.8624
Epoch 86/100
250/250 [==============================] - 0s 544us/step - loss: 0.3370 - accuracy: 0.8633
Epoch 87/100
250/250 [==============================] - 0s 535us/step - loss: 0.3366 - accuracy: 0.8621
Epoch 88/100
250/250 [=======================

In [17]:
# predict whether customer will leave if geography=France, credit_score=600, gender=male, age=40, tenure=3,
# balance=60000, number_of_products=2, has_credit_card=yes, is_active_member=yes, estimated_salary=50000
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.03257644]], dtype=float32)

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
np.set_printoptions(threshold=len(X_train))
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]

 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[1501,   94],
       [ 187,  218]], dtype=int64)

In [20]:
accuracy_score(y_test, y_pred)

0.8595