In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# dataset = pd.read_csv("./data/classification/Cancer_Diagnosis.csv")
dataset = pd.read_csv("./data/classification/Social_Network_Ads.csv")

In [3]:
dataset

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression(random_state = 0)
logistic_classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [8]:
# K nearest neighbors
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [9]:
# Support vector machine
from sklearn.svm import SVC
svm_classifier = SVC(kernel="linear", random_state=0)
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [10]:
# Kernel SVM
from sklearn.svm import SVC
ksvm_classifier = SVC(kernel="rbf", random_state=0)
ksvm_classifier.fit(X_train, y_train)

SVC(random_state=0)

In [11]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
gaussian_classifier = GaussianNB()
gaussian_classifier.fit(X_train, y_train)

GaussianNB()

In [12]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion="entropy", random_state=0)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
# Random forest regression
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, criterion="entropy", random_state=0)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [14]:
# predicted action (purchase or not purchase) based on age and estimated salary by logistic regression
print(logistic_classifier.predict(sc.transform([[30, 87000]])))
# predicted action (purchase or not purchase) based on age and estimated salary by k nearest neighbors
print(knn_classifier.predict(sc.transform([[30, 87000]])))
# predicted action (purchase or not purchase) based on age and estimated salary by support vector machine (svm)
print(svm_classifier.predict(sc.transform([[30, 87000]])))
# predicted action (purchase or not purchase) based on age and estimated salary by kernel svm
print(ksvm_classifier.predict(sc.transform([[30, 87000]])))
# predicted action (purchase or not purchase) based on age and estimated salary by naive bayes
print(gaussian_classifier.predict(sc.transform([[30, 87000]])))
# predicted action (purchase or not purchase) based on age and estimated salary by decision tree
print(dt_classifier.predict(sc.transform([[30, 87000]])))
# predicted action (purchase or not purchase) based on age and estimated salary by random forest regression
print(rf_classifier.predict(sc.transform([[30, 87000]])))

In [15]:
y_pred_logistic = logistic_classifier.predict(X_test)
y_pred_knn = knn_classifier.predict(X_test)
y_pred_svm = svm_classifier.predict(X_test)
y_pred_ksvm = ksvm_classifier.predict(X_test)
y_pred_gaussian = gaussian_classifier.predict(X_test)
y_pred_dt = dt_classifier.predict(X_test)
y_pred_rf = rf_classifier.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred_logistic))
print(accuracy_score(y_test, y_pred_logistic))

print(confusion_matrix(y_test, y_pred_knn))
print(accuracy_score(y_test, y_pred_knn))

print(confusion_matrix(y_test, y_pred_svm))
print(accuracy_score(y_test, y_pred_svm))

print(confusion_matrix(y_test, y_pred_ksvm))
print(accuracy_score(y_test, y_pred_ksvm))

print(confusion_matrix(y_test, y_pred_gaussian))
print(accuracy_score(y_test, y_pred_gaussian))

print(confusion_matrix(y_test, y_pred_dt))
print(accuracy_score(y_test, y_pred_dt))

print(confusion_matrix(y_test, y_pred_rf))
print(accuracy_score(y_test, y_pred_rf))

[[103   4]
 [  5  59]]
0.9473684210526315
[[103   4]
 [  5  59]]
0.9473684210526315
[[102   5]
 [  5  59]]
0.9415204678362573
[[102   5]
 [  3  61]]
0.9532163742690059
[[99  8]
 [ 2 62]]
0.9415204678362573
[[103   4]
 [  3  61]]
0.9590643274853801
[[103   4]
 [  5  59]]
0.9473684210526315
