In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# dataset = pd.read_csv("./data/classification/Cancer_Diagnosis.csv")
dataset = pd.read_csv("./data/classification/Social_Network_Ads.csv")

In [3]:
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression(random_state = 0)
logistic_classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [8]:
# K nearest neighbors
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [9]:
# Support vector machine
from sklearn.svm import SVC
svm_classifier = SVC(kernel="linear", random_state=0)
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [10]:
# Kernel SVM
from sklearn.svm import SVC
ksvm_classifier = SVC(kernel="rbf", random_state=0)
ksvm_classifier.fit(X_train, y_train)

SVC(random_state=0)

In [11]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb_classifier = GaussianNB()
gnb_classifier.fit(X_train, y_train)

GaussianNB()

In [12]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion="entropy", random_state=0)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
# Random forest regression
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, criterion="entropy", random_state=0)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [14]:
# XG boost classification
from xgboost import XGBClassifier
xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [15]:
# # predicted action (purchase or not purchase) based on age and estimated salary by logistic regression
# print(logistic_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by k nearest neighbors
# print(knn_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by support vector machine (svm)
# print(svm_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by kernel svm
# print(ksvm_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by naive bayes
# print(gnb_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by decision tree
# print(dt_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by random forest regression
# print(rf_classifier.predict(sc.transform([[30, 87000]])))
# # predicted action (purchase or not purchase) based on age and estimated salary by random forest regression
# print(xgb_classifier.predict(sc.transform([[30, 87000]])))

In [16]:
y_pred_logistic = logistic_classifier.predict(X_test)
y_pred_knn = knn_classifier.predict(X_test)
y_pred_svm = svm_classifier.predict(X_test)
y_pred_ksvm = ksvm_classifier.predict(X_test)
y_pred_gnb = gnb_classifier.predict(X_test)
y_pred_dt = dt_classifier.predict(X_test)
y_pred_rf = rf_classifier.predict(X_test)
y_pred_xgb = xgb_classifier.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred_logistic))
print(accuracy_score(y_test, y_pred_logistic))

print(confusion_matrix(y_test, y_pred_knn))
print(accuracy_score(y_test, y_pred_knn))

print(confusion_matrix(y_test, y_pred_svm))
print(accuracy_score(y_test, y_pred_svm))

print(confusion_matrix(y_test, y_pred_ksvm))
print(accuracy_score(y_test, y_pred_ksvm))

print(confusion_matrix(y_test, y_pred_gnb))
print(accuracy_score(y_test, y_pred_gnb))

print(confusion_matrix(y_test, y_pred_dt))
print(accuracy_score(y_test, y_pred_dt))

print(confusion_matrix(y_test, y_pred_rf))
print(accuracy_score(y_test, y_pred_rf))

print(confusion_matrix(y_test, y_pred_xgb))
print(accuracy_score(y_test, y_pred_xgb))

[[65  3]
 [ 8 24]]
0.89
[[64  4]
 [ 3 29]]
0.93
[[66  2]
 [ 8 24]]
0.9
[[64  4]
 [ 3 29]]
0.93
[[65  3]
 [ 7 25]]
0.9
[[62  6]
 [ 3 29]]
0.91
[[63  5]
 [ 4 28]]
0.91
[[62  6]
 [ 4 28]]
0.9


In [18]:
from sklearn.model_selection import cross_val_score

accuracies_logistic = cross_val_score(estimator=logistic_classifier, X=X_train, y=y_train, cv=10)
accuracies_knn = cross_val_score(estimator=knn_classifier, X=X_train, y=y_train, cv=10)
accuracies_svm = cross_val_score(estimator=svm_classifier, X=X_train, y=y_train, cv=10)
accuracies_ksvm = cross_val_score(estimator=ksvm_classifier, X=X_train, y=y_train, cv=10)
accuracies_gnb = cross_val_score(estimator=gnb_classifier, X=X_train, y=y_train, cv=10)
accuracies_dt = cross_val_score(estimator=dt_classifier, X=X_train, y=y_train, cv=10)
accuracies_rf = cross_val_score(estimator=rf_classifier, X=X_train, y=y_train, cv=10)
accuracies_xgb = cross_val_score(estimator=xgb_classifier, X=X_train, y=y_train, cv=10)

print("Logistic regression")
print(accuracies_logistic)
print("Accuracy: {:.2f} %".format(accuracies_logistic.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_logistic.std() * 100))
print("\n")

print("Kernel nearest neighbors")
print(accuracies_knn)
print("Accuracy: {:.2f} %".format(accuracies_knn.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_knn.std() * 100))
print("\n")

print("Support vector machine")
print(accuracies_svm)
print("Accuracy: {:.2f} %".format(accuracies_svm.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_svm.std() * 100))
print("\n")

print("Kernel support vector machine")
print(accuracies_ksvm)
print("Accuracy: {:.2f} %".format(accuracies_ksvm.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_ksvm.std() * 100))
print("\n")

print("Gaussian naive bayes")
print(accuracies_gnb)
print("Accuracy: {:.2f} %".format(accuracies_gnb.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_gnb.std() * 100))
print("\n")

print("Decision tree classification")
print(accuracies_dt)
print("Accuracy: {:.2f} %".format(accuracies_dt.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_dt.std() * 100))
print("\n")

print("Random forest classification")
print(accuracies_rf)
print("Accuracy: {:.2f} %".format(accuracies_rf.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_rf.std() * 100))
print("\n")

print("XG boost classification")
print(accuracies_xgb)
print("Accuracy: {:.2f} %".format(accuracies_xgb.mean() * 100))
print("Standard deviation: {:.2f} %".format(accuracies_xgb.std() * 100))

Logistic regression
[0.76666667 0.86666667 0.73333333 0.86666667 0.7        0.66666667
 0.83333333 0.93333333 0.96666667 0.9       ]
Accuracy: 82.33 %
Standard deviation: 9.67 %


Kernel nearest neighbors
[0.83333333 0.96666667 0.76666667 0.93333333 0.86666667 0.9
 0.9        0.93333333 1.         0.96666667]
Accuracy: 90.67 %
Standard deviation: 6.63 %


Support vector machine
[0.76666667 0.8        0.73333333 0.83333333 0.73333333 0.66666667
 0.83333333 0.93333333 0.96666667 0.86666667]
Accuracy: 81.33 %
Standard deviation: 8.84 %


Kernel support vector machine
[0.8        0.96666667 0.8        0.96666667 0.86666667 0.86666667
 0.9        0.93333333 1.         0.93333333]
Accuracy: 90.33 %
Standard deviation: 6.57 %


Gaussian naive bayes
[0.83333333 0.9        0.73333333 0.93333333 0.83333333 0.73333333
 0.86666667 0.96666667 1.         0.96666667]
Accuracy: 87.67 %
Standard deviation: 8.95 %


Decision tree classification
[0.83333333 0.86666667 0.7        0.83333333 0.86666667 0.8