In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
tf.__version__

'2.3.1'

In [3]:
# preprocessing the training set
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)
training_set = train_datagen.flow_from_directory(
        "./data/neural_network/training_set",
        target_size=(64, 64),
        batch_size=32,
        class_mode="binary")

Found 8000 images belonging to 2 classes.


In [4]:
# preprocessing the test set
test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory(
        "./data/neural_network/test_set",
        target_size=(64, 64),
        batch_size=32,
        class_mode="binary")

Found 2000 images belonging to 2 classes.


In [5]:
# initializing the cnn
cnn = tf.keras.models.Sequential()

In [6]:
# convolution
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation="relu", input_shape=[64, 64, 3]))

In [7]:
# pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [8]:
# adding a 2nd convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation="relu"))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [9]:
# flattening
cnn.add(tf.keras.layers.Flatten())

In [10]:
# full connection
cnn.add(tf.keras.layers.Dense(units=128, activation="relu"))
cnn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [11]:
# compiling the cnn
cnn.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [12]:
# training the cnn on the training set and evaluating it on the test set
cnn.fit(x=training_set, validation_data=test_set, epochs=25)

Epoch 1/25
250/250 [==============================] - 64s 255ms/step - loss: 0.6876 - accuracy: 0.5566 - val_loss: 0.6675 - val_accuracy: 0.5965
Epoch 2/25
250/250 [==============================] - 49s 197ms/step - loss: 0.6286 - accuracy: 0.6516 - val_loss: 0.6348 - val_accuracy: 0.6520
Epoch 3/25
250/250 [==============================] - 63s 254ms/step - loss: 0.5847 - accuracy: 0.6873 - val_loss: 0.5436 - val_accuracy: 0.7275
Epoch 4/25
250/250 [==============================] - 49s 195ms/step - loss: 0.5461 - accuracy: 0.7219 - val_loss: 0.5352 - val_accuracy: 0.7390
Epoch 5/25
250/250 [==============================] - 68s 273ms/step - loss: 0.5153 - accuracy: 0.7395 - val_loss: 0.5187 - val_accuracy: 0.7485
Epoch 6/25
250/250 [==============================] - 64s 255ms/step - loss: 0.4940 - accuracy: 0.7577 - val_loss: 0.5182 - val_accuracy: 0.7475
Epoch 7/25
250/250 [==============================] - 48s 194ms/step - loss: 0.4711 - accuracy: 0.7717 - val_loss: 0.5092 - val_ac

In [13]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [14]:
training_set.class_indices

{'cats': 0, 'dogs': 1}

In [15]:
test_image1 = image.load_img("./data/neural_network/single_prediction/cat_or_dog_1.jpg", target_size=(64, 64))
test_image1 = image.img_to_array(test_image1)
test_image1 = np.expand_dims(test_image1, axis=0)  # Convert single image to a batch.
cnn.predict(test_image1)

array([[1.]], dtype=float32)

In [16]:
test_image2 = image.load_img("./data/neural_network/single_prediction/cat_or_dog_2.jpg", target_size=(64, 64))
test_image2 = image.img_to_array(test_image2)
test_image2 = np.expand_dims(test_image2, axis=0)  # Convert single image to a batch.
cnn.predict(test_image2)

array([[0.]], dtype=float32)

In [19]:
cnn.save("./trained_model/cnn_cat_dog_images")

INFO:tensorflow:Assets written to: ./trained_model/cnn_cat_dog_images\assets


In [21]:
loaded_cnn = tf.keras.models.load_model("./trained_model/cnn_cat_dog_images")

In [25]:
loaded_cnn.predict(test_image1)

array([[1.]], dtype=float32)

In [26]:
loaded_cnn.predict(test_image2)

array([[0.]], dtype=float32)